version : '3.3'
services:
  node:
    container_name: project_node
    image: 'node:latest'
    working_dir: /home/node/app
    command:
    - /bin/sh 
    - '-c'
    - 'npm install && npm start'
    ports:
    - '3000:3000'
    volumes:
    - './src:/home/node/app'